version = 0.1

[default.deploy.parameters]
stack_name = "sheglow-dev2"
resolve_s3 = true
s3_prefix = "sheglow-dev2"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=\"dev\""
image_repositories = []
